### ISSUE TITLE
Repeated warnings in postfix mail.warn file

### ISSUE THREAD

**Issue by M-Stenzel** [tachtler/FooterMilter#1]
Periodically I receive this in latest releases postfix mail.warn file, using latest footermilter software

postfix/cleanup[]: warning: milter inet:localhost:10099: can't read SMFIC_HEADER reply packet header: Application error

In the footermilter logs there is no corresponding error.

Any clue?

P. S. Java Version is 1.8, update 391 (from Oracle), OS is Linux x86_64

**Comment by tachtler** [comment]
Hello M-Stenzel,

I have a **new version** in which the line length check is no longer active for `org.apache.james.mime4j`. This is not really a satisfactory state, but I am also aware that there is software that does not necessarily create e-mails according to RFC-5321.

Would it be possible for me to send you a **new `FooterMilter.jar`** (also compiled with Java 1.8) and for you to replace it and then test it?

You can answer me to: **klaus@tachtler.net**

Thanks and best regards
Klaus.

**Comment by tachtler** [comment]
Hi,

I can see this only with bounce e-Mails of mailing lists at my server.

Greetings
Klaus.

**Comment by tachtler** [comment]
Hi M-Stenzel,

I have also checked my installation. This occurs when bounce e-mails are received by mailing lists. This is also the case with `opendmarc-milter`, for example. As long as the "**warning**" `Success` is displayed at the end, this is not a problem in my opinion.

I hope the problem with program crashes no longer occurred with my test version?

Regards
Klaus.

**Comment by M-Stenzel** [comment]
Currently I receive:
2024-04-14T17:42:58.877957+03:00 terve postfix/submission/smtpd[47575]: warning: milter inet:localhost:10099: can't read SMFIC_CONNECT reply packet header: Application error

**Comment by tachtler** [comment]
Hi,

this is extrem confusing, because i can't reproduce the application error. And it's in the connection section of the milter.

Which OS and java Version?

Thank you,
Klaus.

**Comment by M-Stenzel** [comment]
openSuSE linux, java version 1.8.0_391-b13

**Comment by tachtler** [comment]
Hi,

can you add the parameter **`-d`** inside the footermilter.service systemd start file, shown as below:
```
[Unit]
Description=FooterMilter Java Service
Requires=network.target
After=network.target

[Service]
SuccessExitStatus=143
WorkingDirectory=/opt/FooterMilter
ExecStart=/usr/bin/java -jar FooterMilter.jar -c footermilter.ini -d
TimeoutStopSec=5
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
**This is the line to change**:
`ExecStart=/usr/bin/java -jar FooterMilter.jar -c footermilter.ini -d`
and make also a 
`systemctl daemon-reload`
`systemctl restart footermilter.service`
You can see, that the LOG-file will grow, with every e-mail under the path: `/var/log/FooterMilter.log`

Maybe, you can see what happen, if the error at SMFIC_CONNECT occurs?

Thank you for your help!
Klaus.

**Comment by M-Stenzel** [comment]
Hi, 
an important update on the issue.
The mail server serves Deltachat clients [https://delta.chat/de/](https://delta.chat/de/)

Yesterday I sent a message, 33 MB (more than the usual size), and I verified this morning.
The error seems to occur ONLY with bigger mails. I did not check, what exactly the size needs to be to cause the error, yet, but this seems to be the issue.
Maybe you can verify with a bigger size mail, if you are affected, too.

Martin.

**Comment by tachtler** [comment]
Hi Martin,

what error message occurs? 
SMFIC_CONNECT, SMFIC_BODY, SMFIC_HEADER... this would be important for me too.

Thank you.
Klaus.

**Comment by tachtler** [comment]
Hi Martin,

I have carried out some tests with a test system and with my live system and cannot confirm the problems with large e-mails (whereby I allow a maximum of 20 MB as a size).

But I have sent you two e-mails with a new version.
(Please note the second e-mail, the first one from me with an included version still had a bug).

Thank you in advance!
Klaus.

**Comment by M-Stenzel** [comment]
> Hi Martin,
> 
> what error message occurs? SMFIC_CONNECT, SMFIC_BODY, SMFIC_HEADER... this would be important for me too.
> 
> Thank you. Klaus.

Hi Klaus,

different messages:
terve postfix/cleanup[20218]: warning: milter inet:localhost:10099: can't read SMFIC_HEADER reply packet header: Application error
terve postfix/cleanup[46073]: warning: milter inet:localhost:10099: can't read SMFIC_BODYEOB reply packet header: Application error
terve postfix/cleanup[61504]: warning: milter inet:localhost:10099: can't read SMFIC_BODY reply packet header: Application error

The three different messages did not appear simultaneously,

Martin.

**Comment by tachtler** [comment]
Hi Martin,

add new version 1.2 - Thank you so much for testing!

From time to time, a few warnings appear if a certain area cannot be read by the milter. However, this is only an indication and should not affect the functionality. As already mentioned, this also happens with other milters, which then also work without problems, e.g. the OpenDMARC-milter.

Many thanks again and best regards
Klaus.
