### ISSUE TITLE
Maximum header length limit error message

### ISSUE THREAD

**Issue by M-Stenzel** [tachtler/FooterMilter#2]
Same software setup as in Issue #1

In the logs I receive
2024-04-03 20:55:19,765 [ERROR] [FooterMilterException                   ] [InitException                           ] ***** Program stop, because FooterMilter detects a runtime error! ***** (For more details, see error messages and caused by below).
2024-04-03 20:55:19,771 [ERROR] [FooterMilterException                   ] [<init>                                  ] Caused by: org.apache.james.mime4j.MimeIOException: Maximum header length limit (10000) exceeded

In my footermilter.ini, there are only a few lines of entries added...

Any clue?

**Comment by tachtler** [comment]
Hello M-Stenzel,

the problem with the error message "`org.apache.james.mime4j.MimeIOException: Maximum header length limit (10000) exceeded`" has nothing to do with the length of your `footermilte.ini `file. 

I am currently analyzing the code and will get back to you.

**Comment by tachtler** [comment]
Hi M-Stenzel,

**[https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3.1.6](https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3.1.6)** → 

```
[4.5.3.1.6](https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3.1.6).  Text Line

   The maximum total length of a text line including the <CRLF> is 1000
   octets (not counting the leading dot duplicated for transparency).
   This number may be increased by the use of SMTP Service Extensions.
```
I think the problem lies in the line length.

**Comment by tachtler** [comment]
Hello M-Stenzel,

I have a **new version** in which the line length check is no longer active for `org.apache.james.mime4j`. This is not really a satisfactory state, but I am also aware that there is software that does not necessarily create e-mails according to RFC-5321.

Would it be possible for me to send you a **new `FooterMilter.jar`** (also compiled with Java 1.8) and for you to replace it and then test it?

You can answer me to: **klaus@tachtler.net**

Thanks and best regards
Klaus.

**Comment by M-Stenzel** [comment]
It works now, thank you!!!

**Comment by tachtler** [comment]
Hi,

thank you, for your testing and your relay.

Klaus.

**Comment by tachtler** [comment]
I close this issue.
