### ISSUE TITLE
Footer charset

### ISSUE THREAD

**Issue by borodaxel** [tachtler/FooterMilter#3]
Users may send emails in different charsets. Is it possible to add automatic conversion to charset specified in the email, assuming that the ini-file is in utf-8?

**Comment by tachtler** [comment]
Hi borodaxel,

the FooterMilter does not change the character set. The data that is added in text or HTML format is added to the body of the e-mail without affecting the character set of the e-mail.

The content of the ini-file is read in as UTF-8.

Greetings
Klaus.

**Comment by borodaxel** [comment]
It does not change the character set header, but it breaks the content of the email. If the character set of the email is utf-8 - adding footer works fine. With other character sets the content becomes broken. I can't even find the path to recover the broken character set.

I think this may be caused by mime4j library if footer content is added without proper character set conversion.

The original email:
![изображение](https://github.com/tachtler/FooterMilter/assets/4837605/9b5da7d6-ee9a-4b39-994a-fc96223ce7ec)

With added footer. It definitely changed the number of bytes for 8-bit encoding:
![изображение](https://github.com/tachtler/FooterMilter/assets/4837605/a25c85a9-600e-4f4f-9513-43b011dbf255)

**Comment by tachtler** [comment]
Hi borodaxel,

thank you for the detailed explanation. **I will have a look at it.** 

Many thanks and best regards
Klaus.

**Comment by borodaxel** [comment]
Sorry for bothering... I looked through the code and made some debugging. There are some points:

- mime4j `DefaultMessageBuilder.parseMessage` accepts `ByteArrayInputStream`
- jmilter `AbstractMilterHandler.body` defined as `body(MilterContext context, byte[] bodyChunk) `
- however `FooterMilterHandler.body` defined as `body(MilterContext context, String bodyChunk)`

I may be wrong, but in this case byte array is converted to Unicode string, and `DefaultMessageBuilder.parseMessage` receives the Unicode byte sequence instead of raw bytes. This is not right for non-Unicode emails.

As far as I know headers are always encoded somehow and could be treated as US_ASCII bytes. But body chunks should be collected as bytes (we don't know the charset yet). Then before parsing the whole message we need to combine header bytes with body bytes and pass them to `DefaultMessageBuilder.parseMessage`. Hopefully after that we can change the content according to its charset and encoding.

Thank you in advance, my best regards!

PS: I compared jmilter versions. FooterMilter uses 0.3.6. But `body()` definition was changed to `body(MilterContext context, byte[] bodyChunk) ` in version 0.5.

**Comment by tachtler** [comment]
Hi borodaxel,

can I sent you an experimental FooterMilter.jar for testing → you can e-mail me at: klaus@tachtler.net

Thank you in advance.
Klaus.

**Comment by tachtler** [comment]
Hi borodaxel,

can I sent you an experimental FooterMilter.jar for testing → you can e-mail me at: [klaus@tachtler.net](mailto:klaus@tachtler.net)

Thank you in advance.
Klaus.

**Comment by tachtler** [comment]
Hi borodaxel,

add new version 1.2.

Greetings
Klaus.
