### ISSUE TITLE
Feature request: Possibility to disable Footer Milter for defined mail recipients  

### ISSUE THREAD

**Issue by M-Stenzel** [tachtler/FooterMilter#4]
Hi,

I use the Deltachat software. 
Today I got this response:

_Martin Stenzel/dc: Could you please remove your signature from the end of all of your messages?_

For the purpose of using my mail address with Deltachat I need to make sure that there is no footer when sending to this specific mail address.

Feature request: Make it possible to disable FooterMilter for defined mail address recipients.
There is no EASY (if at all) way to bypass postfix milters for defined mail addresses.

Thanks, Martin.

**Comment by tachtler** [comment]
Hi Martin,

I think, I will not have the resources to that in the near future.

Greetings
Klaus.

**Comment by tachtler** [comment]
Hi Martin,

maybe you can sent as martin+deltachat@yourdomain.tld, than no footer will be added?

Greetings
Klaus.

**Comment by M-Stenzel** [comment]
yes, good idea. Using the regular address with Deltachat poses additional complexity. A dedicated user (mail address) for the sole purpose of messaging is the easiest way.

**Comment by tachtler** [comment]
Hi,

I think the possibility to exclude e-mail recipient addresses from the footer creation would increase the complexity of the configuration and would also not be expedient for possibly very few application scenarios. 

Using a separate e-mail address for such exceptions certainly makes more sense and is also easier to implement.

Thank you and best regards
Klaus.
